name: Ansible Test
on:
  - push
  - pull_request
  - workflow_dispatch
env:
  TOX_LSR: "git+https://github.com/linux-system-roles/tox-lsr@2.13.1"
jobs:
  ansible_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install tox, tox-lsr
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          sudo apt-get update
          sudo apt-get install -y git
          pip install "$TOX_LSR"
      - name: Convert role to collection format
        run: |
          TOXENV=collection lsr_ci_runtox
      - name: Run ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.14
          testing-type: sanity
          collection-src-directory: .tox/
