name: Ansible Plugin Scan
on:
  - push
  - pull_request
  - workflow_dispatch
env:
  TOX_LSR: "git+https://github.com/linux-system-roles/tox-lsr@2.13.1"
jobs:
  ansible_plugin_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install tox, tox-lsr
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          sudo apt-get update
          sudo apt-get install -y git
          pip install "$TOX_LSR"
      - name: Run ansible-plugin-scan
        run: |
          set -euxo pipefail
          TOXENV=ansible-plugin-scan lsr_ci_runtox
