# yamllint disable rule:line-length
name: tox
on:  # yamllint disable-line rule:truthy
  - pull_request
env:
  TOX_LSR: "git+https://github.com/linux-system-roles/tox-lsr@2.3.0"
  LSR_ANSIBLES: 'ansible==2.8.* ansible==2.9.*'
  LSR_MSCENARIOS: default
  LSR_EXTRA_PACKAGES: "libdbus-1-dev libgirepository1.0-dev python3-dev libssl-dev libcairo2-dev python2-dev"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: ['2.7', '3.6', '3.7', '3.8']
    steps:
      - name: checkout PR
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyver }}
      - name: Install platform dependencies, python, tox, tox-lsr
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          sudo apt-get update
          sudo apt-get install git
          pip install "$TOX_LSR"
          lsr_ci_preinstall
      - name: Run tox tests
        run: |
          set -euxo pipefail
          tox_lsr_path=$(pip show tox-lsr 2> /dev/null | awk '/^Location: / {print $2}')
          source "$tox_lsr_path/tox_lsr/test_scripts/utils.sh"
          toxenvs_for_sys=""
          if lsr_venv_python_matches_system_python; then
            toxenvs_for_sys=",ansible-lint,collection,ansible-test"
          fi
          toxpyver=$(echo "${{ matrix.pyver }}" | tr -d .)
          toxenvs="py${toxpyver}"
          case "$toxpyver" in
          27) toxenvs="${toxenvs},coveralls,flake8,pylint,custom${toxenvs_for_sys}" ;;
          36) toxenvs="${toxenvs},coveralls,black,yamllint,shellcheck,custom${toxenvs_for_sys}" ;;
          37) toxenvs="${toxenvs},coveralls,custom${toxenvs_for_sys}" ;;
          38) toxenvs="${toxenvs},coveralls,custom${toxenvs_for_sys}" ;;
          esac
          TOXENV="$toxenvs" lsr_ci_runtox
